language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: EEfIPr086H2Ibghcypo7NViGHIYwgbQqe1L/wBO3ononpMu8SkBrMTkvPZytOGxgHh1FJrZdnoT1m1tI2EfYCb35BJQG4vydCiEhOImVcoDXNnPAz9QNRP/6i0iNYCXTg1S3XIfP9iI29CRooXzMHo3xxBC2MFfygwk43NWu4TA4JsD30osAMyaUKbTcq/k7hBpy+tz2an5vp6YxGBHjxxuCIksk9vGMhqyFtifxGmxZtyf7DdKcAJsf3czJMWzxQmUxgJK92bDHIcF5fqiwcNtFgDGu+eG6ePgrqvyuOq54iZTBREfoLaawKuDn5pC1PKRc+fKr7+NpYSfCVUm3DCe4RmH+5cnDi3W1XtIugjnv5s3ntY7AFt5NKtZoMCgYc1HBYccz5GpHNTMxA2lj4Sz6nB6UBslXbl6MPpuCemWX09zJaXlcDgZyYBMhybtPciAGoxHwsBouMrB9WEgdADAYZOZXe+N/uxK0LITrJ6CH181M0ZRp8msi/29/zT3jjDTeE7MMvGXbyGR68CqIujfwJDpRq60+8UYRjurWDYEpdzr2KjeW9XXFSpkfT6Gm46cDOdMEVerKO0hWF2A+r8yGqnkQFlPnjrhx76DwaotYCNXjCPmbCOjJd5hI8g2E4YDQzTUrUgQtAFGghP8QdPvrl2dBlINBJBFgv2Nl6bg=
  app: whispering-woodland-60895
  on:
    repo: azhou125/blog-app-with-tests
