language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: C68jzL8ZjVl+FOTomU0S61xyym0eatchNnOvUjJuT6mCEdvtEDQzBbbi3SwZSjOT8Yw4jlh3hTZrtlukT61fjPTshX3zoAcT0w2dfbk28C2cP0sX9qHik2eKLGl2OyMJC7jd6FYeqVsukb1fDHqwI4T6EDyaZ5F7DgFHglCYd3fu/ilEPxYjzu4iCJZYhk4temWx40tw9cUoZ6qljZOO2j2cOwXy1oxm0IyVj9olofO9VRb3ab+rVTb0Etmp1WTyuzHs/w4Dww3e24rtBM/fKBXQBinuq+ExKwCLpt3fIENyTfvq5lly8MdLGmxPcpNridS6CInVXGlmOJFBZluIeNtep6ldq2gVrTxgeiDBujMIcKZ4/yBWBqaI37+rpAhbbmKh+w0XhmpipNeZjzfig+d5YCtpdgER/GEnuwOv5VuO4WXLlmNwH5vwpJzDlX/rVa/zeAQnYOmJ6yT+230zGSkdp+msZLI5ZMHpir5LoIDdAjs7z4W4ZRuiRbx0SkJpfbzVtLXWcLNTtDjHyy/q36P4JzV9O+cccMglw1q2K1kB/JgD3jUN1JwloFI2sv4Mvtte1/ZVli56PUU3TWbGDvRq9UKkAP4M0iSsB2LvMCN7+TJ/6baLh74zVyiPV1/CRQKXAtDTt2nIm3jkA35Gche5QEXbE0FDLD4iAoJtRNo=
  app: blog-app-with-tests
  on:
    repo: azhou125/blog-app-with-tests
