language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: rRKOARWU/ELINiwX3xUOXfWFfYMhHdgntq7bCD3rQf0fY9qatIFX1L0hHK1fdIZlvZgmgggBOoaKMYxw6iUgTSjiBY/S2KtrwXgyLy191awUa48hnHI4ViNVTSUNHlzUk6TKfsSC/Tbs3MaoYuZ2ofo9ySAClCRaEm5bJMnmqOp6sypSQ5HVSf75boibLOwU2IDPif6L0EmMQllDmQyhNhk4fnDGJNdVBMq2d2gr52J80N3pbSOsRQuvIo7Wr8xzKb4NzzOtVZH2f5HC7ATSIJ5rhiu061BU/9Wha0rOSMl6dCmEdee2RAcJdMCVbOw7fLX5h5wJRd9Qm9gVv1Z4MPplBwDemB+8Jh40SSOFQXL0rSwoqjAh6f04AQIsvi5+oRDdVS+bxXNu8Jvz7zB/ZVGLENR16/MTzxuErPgc2PScu8Y2rMjVsqTXYJkZdTMUVHp+ua4jbK1HxyOldxHq58kb7tNdYMUG83qFGnkK7AJhwQRjg8jyK78dGyM30OiGbrDHeL+8a3xNU2eORNuYgfSeoRxRgJQIdO0FMKZF8/YyRlGu3H/6SsrGh021YBtxPme44ZID6Ome2a0iVEC7x0qv+lrK5BPSfUoUv4jXd3IHaxLum4iiBTDW8uv6IiKucy4H3w1ZS0ZpBBMYhW9UHoOSVKQEKLrUNwBT9MojrfU=
  app: whispering-woodland-60895
  on:
    repo: azhou125/blog-app-with-tests
